### ISSUE TITLE
Reverse for 'app_list' not found error on Django 1.10.8, python 2.7.12

### ISSUE THREAD

**Issue by wimfeijen** [divio/django-simple-sso#24]
Reverse for 'app_list' with arguments '()' and keyword arguments '{'app_label': u'sso_server'}' not found. 1 pattern(s) tried: [u'admin/(?P<app_label>vouchers|pages|redirects|auth|homepage|mezzanine_blocks|blog|forms|conf|formulieren|videos|galleries|sites|begrippen|generic|registration)/$']

---
Here is the Traceback:

Environment:

Request Method: GET
Request URL: http://test.go2people.nl:9012/admin/

Django Version: 1.10.8
Python Version: 2.7.12
Installed Applications:
(u'mezzanine.boot',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.pages',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.galleries',
 u'mezzanine.twitter',
 u'crispy_forms',
 u'mezzanine_blocks',
 u'registration',
 u'simple_sso.sso_server',
 u'begrippen',
 u'formulieren',
 u'homepage',
 u'videos',
 u'vouchers',
 u'zoeken',
 u'debug_toolbar',
 u'compressor',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django_comments')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware',
 u'vouchers.middleware.VoucherMiddleware',
 u'debug_toolbar.middleware.DebugToolbarMiddleware')

Traceback:

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/contrib/admin/sites.py" in wrapper
  229.                 return self.admin_view(view, cacheable)(*args, **kwargs)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/contrib/admin/sites.py" in inner
  211.             return view(request, *args, **kwargs)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/contrib/admin/sites.py" in index
  468.         app_list = self.get_app_list(request)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/contrib/admin/sites.py" in get_app_list
  451.         app_dict = self._build_app_dict(request)

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/contrib/admin/sites.py" in _build_app_dict
  436.                         current_app=self.name,

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/urls/base.py" in reverse
  91.     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))

File "/var/virtualenvs/machinistgrondverzet2/local/lib/python2.7/site-packages/django/urls/resolvers.py" in _reverse_with_prefix
  392.             (lookup_view_s, args, kwargs, len(patterns), patterns)

Exception Type: NoReverseMatch at /admin/
Exception Value: Reverse for 'app_list' with arguments '()' and keyword arguments '{'app_label': u'sso_server'}' not found. 1 pattern(s) tried: [u'admin/(?P<app_label>vouchers|pages|redirects|auth|homepage|mezzanine_blocks|blog|forms|conf|formulieren|videos|galleries|sites|begrippen|generic|registration)/$']

-----
pip freeze

backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bleach==2.1.2
certifi==2017.11.5
chardet==3.0.4
confusable-homoglyphs==2.0.2
decorator==4.1.2
Django==1.10.8
django-appconf==1.0.2
django-compressor==2.2
django-contrib-comments==1.8.0
django-crispy-forms==1.7.0
django-debug-toolbar==1.9.1
django-registration==2.3
django-simple-sso==0.11
enum34==1.1.6
filebrowser-safe==0.4.7
future==0.16.0
gevent==1.2.2
grappelli-safe==0.4.7
greenlet==0.4.12
gunicorn==19.7.1
html5lib==1.0.1
idna==2.6
ipdb==0.10.3
ipython==5.5.0
ipython-genutils==0.2.0
itsdangerous==0.24
Mezzanine==4.2.3
-e git://github.com/renyi/mezzanine-blocks.git@2983557c03f16625c63954c4e386915a8eb7e549#egg=mezzanine_blocks
oauthlib==2.0.6
pathlib2==2.3.0
pexpect==4.3.1
pickleshare==0.7.4
Pillow==5.0.0
pkg-resources==0.0.0
prompt-toolkit==1.0.15
psycopg2==2.7.3.2
ptyprocess==0.5.2
Pygments==2.2.0
pytz==2017.3
rcssmin==1.0.6
requests==2.18.4
requests-oauthlib==0.8.0
rjsmin==1.0.12
scandir==1.6
simplegeneric==0.8.1
six==1.11.0
sqlparse==0.2.4
traitlets==4.3.2
tzlocal==1.5.1
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
webservices==0.7
xlrd==1.1.0

**Comment by zodman** [comment]
Works for django 1.11

```
class SSO_Server(Server):
    auth_view_name = "admin:login"
 
SSOServer = SSO_Server()
```

**Comment by mshvern** [comment]
this still occurs, for now I bypass it with 

```
class SSOServer(Server):

    def register_admin(self):
        pass

```
auth_view_name is unrelated.

**Comment by chriggi** [comment]
Bump, I'm getting the exact same error. 
I added: 'simple_sso.sso_server' to INSTALLED_APPS, everything else works (sso with client works fine) but the admin page is broken now.

**Comment by chriggi** [comment]
Thanks to kezabelle (from #django IRC) this is the solution:
You have to instantiate the server before the admin url:

```
sso_server = SsoServer()

urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('api/account/', include('account.urls')),
    path('api/accounts/', include('rest_registration.api.urls')),
    path('api/', include('data.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += [
    path('api/server/', include(sso_server.get_urls())),
]

```
