### ISSUE TITLE
webservices==0.7 uses request.raw_post_data

### ISSUE THREAD

**Issue by XaviP** [divio/django-simple-sso#32]
It seems that webservices==0.7 uses request.raw_post_data, instead of request.body (django>1.6)
Here's the error on py3, dj1.11, django-simple-sso==0.13.2:
```
AttributeError at /server/request-token/
'WSGIRequest' object has no attribute 'raw_post_data'
```
Here some explanation:
https://stackoverflow.com/questions/22368190/django-cant-access-raw-post-data#answer-22368223

**Comment by nbxorg** [comment]
I've noticed this when directly accessing `^request-token/$`

However in `webservices/sync.py` there's this:

```python
if getattr(request, 'body', None):
    signed_data = request.body
else:
    signed_data = request.raw_post_data
```

**Comment by nijel** [comment]
IMHO this error happens only when you do a GET request on the endpoint expecting POST. The easiest workaround would be to wrap `provider_for_django` with `require_POST`
