### ISSUE TITLE
TypeError: manager_method() keywords must be strings

### ISSUE THREAD

**Issue by HashimJaved09** [divio/django-simple-sso#37]
After installing the django-simple-sso and running "python manage.py migrate", this error occurs and I couldn't figure its solution out. Can anyone help me out on this.

while self.get_model().objects.filter(**{self.field: key}).exists():
**TypeError: manager_method() keywords must be strings**

**Comment by lijianbing** [comment]
django-simple-sso/simple_sso/sso_server/migrations/0001_initial.py
 ('private_key', models.CharField(default=simple_sso.sso_server.models.ConsumerSecretKeyGenerator(b'private_key'), unique=True, max_length=64)),

bytes  b'private_key' will produce above error.
you need rm django-simple-sso/simple_sso/sso_server/migrations/00*.py
then  makemigrations  again

**Comment by lijianbing** [comment]
remove four  b from 0001_initial.py will fix

**Comment by ezequielarevalo-natgeo** [comment]
I came across the same issue, any update about it ?

**Comment by HashimJaved09** [comment]
@ezequielarevalo-natgeo no!

**Comment by GaretJax** [comment]
This has been fixed and released as part of 0.14.1
