### ISSUE TITLE
If the server requests the page from the client

### ISSUE THREAD

**Issue by qq854051086** [divio/django-simple-sso#41]
I tested the token request from the client to the server, and it passed easily. When I jump from the service side to the client side, it is normally directly passed and does not need to be verified. Has it been implemented, and how can I operate it?

**Comment by FinalAngel** [comment]
@victor-yunenko any insights from your end?

**Comment by shivshankarkeshari** [comment]
Would you please, share any Github repo where you applied django-simple-sso?

**Comment by FinalAngel** [comment]
@shivshankarkeshari please have a look at https://github.com/divio/aldryn-sso which implements django-simple-sso

**Comment by qq854051086** [comment]
Thanks for your reply, my problem is solved. My actual situation is that I need to connect to the authentication server. As a client, I receive verification and user information.

**Comment by FinalAngel** [comment]
thanks for the feedback @qq854051086
