### ISSUE TITLE
Add installation instructions to README

### ISSUE THREAD

**Issue by shehrojkhan786** [divio/django-simple-sso#42]
Hi,

I am really sorry to use this platform for asking this.
Could do you provide example source code for reference.
As per example "https://micropyramid.com/blog/django-single-sign-on-sso-to-multiple-applications/"
given here i am unable to run django-admin dbshell to create keys.

Sorry again for using this platform.
Thanks
Shehroj Khan

**Comment by RafaelFigueiredo** [comment]
@shehrojkhan786 you can generate the keys directly on django-admin.
![image](https://user-images.githubusercontent.com/7611174/93642267-2b1e2400-f9d4-11ea-82ca-379867687a1f.png)
